displays run validation at the text field
NLueg/FaPra-partielle-sprachen pull request #13
Opened 2022-05-20 08:14 UTC by MarcelSanders

Fehler/Warnungen bei der Validierung eines Runs werden am Textfeld angezeigt (Icon + Tooltip).
Es werden keine doppelten Fehler/Warnungen angezeigt und vor einem neuen Parsen werden bestehende Fehler/Warnungen gelöscht.
Warnungen werden am Run selbst gespeichert, damit diese nachher beim Durchschalten der Runs erhalten bleiben.
Zusätzliche Warnmeldungen, wenn ein Arc oder Transition doppelt vorkommen.
Die Referenzierung von Transitions in Arcs wird überprüft und bei nicht vorhandenen Transitions eine Warnmeldung angezeigt (Die Prüfung der Referenzierung wird nachher auch für den Sugiyama benötigt)

2022-05-20 12:53 UTC, NLueg requested changes

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.ts
> +}
_Nice to have_:

Ich bin mittlerweile ein Fan von Types, da man solche Sachen wie `public Valid = Valid;` dann nicht braucht um es im Template zu verwenden.
Du hast dann trotzdem auch Autovervollständigung und Co. aber brauchst diesen (ziemlich unschönen) Zwischenschritt nicht.

Ein weiterer Vorteil ist, dass du gleich einen "schönen String" hast, den du auch z.B. speichern kannst. Bei einer Enum, wo keine Werte zu gewiesen werden, ist alles basierend auf dem Index der Enum. Spielt bei uns weniger ne Rolle, aber wollte ich noch mit erwähnen.

Den export brauchst du vermutlich auch gar nicht, zumindest habe ich keine Verwendung außerhalb der Datei gesehen.

```suggestion
type ValidationStatus = 'error' | 'warn' | 'success'
```

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.ts
> +            this._isRunValid = Valid.Error;
_Nice to have_
Weiterführung von `enum` -> `type`

```suggestion
            this.runValidationStatus = 'error';
```

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.ts
> +            this._isRunValid = Valid.Warn;
_Nice to have_
Weiterführung von `enum` -> `type`

```suggestion
            this.runValidationStatus = 'warn';
```

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.ts
> +            this._isRunValid = Valid.Success;
_Nice to have_
Weiterführung von `enum` -> `type`

```suggestion
            this.runValidationStatus = 'success';
```

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.ts
> +    private _isRunValid: Valid | undefined;
Ist genaugenommen eher sowas wie `_runValidationStatus`
```suggestion
    runValidationStatus: ValidationStatus | undefined;
```

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.scss
> +    color: #4CAF50;
_Nice to have:_

Ich bin Fan davon, sowas wie Farben global verfügbar zu haben, damit man nicht immer die gleichen Farben kopiert, die man hinterher vielleicht auch nochmal anpassen muss/möchte.
Das kann man relativ easy über CSS-Custom-Properties machen.

Dazu muss man zur Datei `styles.css` den folgenden Block hinzufügen:

```scss
:root {
    --success-color: #4CAF50;
}
```

Damit legst du global unter der Variable `--sucess-color` diese Farbe fest.
Verwenden kannst du es dann einfach so:

```suggestion
    color: var(--success-color);
```

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.scss
> +::ng-deep .mat-tooltip {
Das gerne einfach zur `styles.css` hinzufügen, das brauchen wir ja auf jeden Fall global und dann vermeidet man auch das `::ng-deep`

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.html
> +                </mat-icon>
_Nice to have:_

Hier könnte man auch gut mit einem Switch arbeiten:

```suggestion
                <ng-container [ngSwitch]="runValidationStatus">
                    <mat-icon *ngSwitchCase="'success'" class="color_success">
                        check_circle
                    </mat-icon>
                    <mat-icon *ngSwitchCase="'warn'" class="color_warning">
                        warning_amber
                    </mat-icon>
                    <mat-icon *ngSwitchCase="'error'" class="color_error">
                        error_outline
                    </mat-icon>
                </ng-container>
```

2022-05-20 12:53 UTC, NLueg commented on src/app/app.component.ts
Solche TypeScript getter sind immer schlecht in Templates bzw. bei der Verwendung innerhalb von Templates. Für Angular sind getter auch normale Methode-Aufrufe und damit kommt die Change-Detection von Angular leider gar nicht klar.
Methoden werden unfassbar oft von Angular aufgerufen, weil Angular logischerweise nicht erkennt, wenn sich etwas ändert. Das ist anderes, wenn man direkt die Property im Template verwendet.
Das kann man leicht nachvollziehen, wenn man hier in den Getter einfach mal einen `console.log` einbaut

```suggestion
```

2022-05-21 17:55 UTC, MarcelSanders commented on src/app/app.component.ts
> +    }
Wieder was gelernt , war mir gar nicht so bewusst:)

Wie müsste das dann am besten ablaufen, wenn ich das Run Array bearbeite?
Wenn ich das wie folgt machen würde, müsste ich dann immer .next ( -> "this.runs$.next(this.runs);") aufrufen?.

```ts
 public get runs(): Run[] {
        return this.runs$.getValue();
    }

public registerRun(run: Run): void {
        //add run or update current run if empty
        if (this.currentRun.isEmpty() && this.runs.length > 0) {
            this.updateCurrentRun(run);
        } else {
            this.runs.push(run);
            this.display(run);
        }
        this.runs$.next(this.runs);
    }
```

Oder hast du vielleicht Zeit das einmal komplett zu korrigieren?

2022-05-22 09:08 UTC, NLueg approved these changes

2022-05-22 09:09 UTC, merged