Par 38/merge runs
NLueg/FaPra-partielle-sprachen pull request #25
Opened 2022-06-20 17:32 UTC by NLueg

2022-06-20 17:33 UTC, NLueg commented on src/app/classes/diagram/arc.ts
> -import { Element } from './element';
Durch das Entfernen dieser Referenz verliert man im Endeffekt nichts, weil man das `label` des Elements hat, was im Grunde wie eine ID ist.

2022-06-20 17:36 UTC, NLueg commented on src/app/services/layout.service.ts
> +            const elementsWithIncomingArcs = arcs.map((a) =>
gegeben: Der Code ist hier jetzt nicht wirklich schöner geworden.
Vorher wurde sich jedoch bei der Funktion indexOf darauf verlassen, dass man auch 1:1 die gleiche Referenz hat (ähnlich wie == bei Java). Hier brauchen wir aber eher ein Equals was von Hand umgesetzt werden muss.

2022-06-21 08:05 UTC, MarcelSanders requested changes

2022-06-21 09:44 UTC, NLueg commented on src/app/components/display-merged-run/merge.service.ts
> +        return;
Jep, vollkommen richtig. Vielen Dank!

2022-06-21 11:09 UTC, NLueg commented on src/app/components/display-merged-run/merge.service.ts
> +            const baseStart = getStartOfRun(baseRun);
Das ist auf jeden Fall ein guter Punkt. Ich denke, das sollten wir nochmal abklären.
Ich glaube, wenn man den gemergten Run "aufteilt" wäre das ein falscher Ablauf, weil im alten Run ja theoretisch beide Startpunkte aufgerufen werden müssen, um den Run zu durchlaufen.
Vermutlich sollte die Logik so sein, dass man dann beide Startpunkte voraussetzt.

Ich würde vorschlagen, das `Handling von mehreren Startpunkten beim Mergen` als separates Ticket mit aufzunehmen und das dann nach der Klärung nächste Woche anzugehen.

2022-06-23 09:21 UTC, NLueg commented
Die Änderungen für das Verschieben müssen jetzt noch für die Merge-View übertragen werden.

2022-06-23 12:10 UTC, MarcelSanders approved these changes

2022-06-23 12:12 UTC, merged