Par 44
NLueg/FaPra-partielle-sprachen pull request #31
Opened 2022-06-28 12:34 UTC by ElisabethBrandl

within the svg-service it is checked if arcs and transitions should be highlighted

highlightcolor can be changed in the new color-service

minor code changes for the resetButton (just the naming) and deletion of some not needed code

2022-07-05 04:53 UTC, NLueg requested changes

2022-07-05 04:53 UTC, NLueg commented on src/app/services/svg/svg.service.ts
> +                    if (element.label == el.label) {
Hier fehlt vermutlich noch sowas, dass man überprüft, dass die Kanten auch dieselben sind, oder?
Aktuell ist es noch so, dass z.B. bei den Beispielen `t6` mit markiert wird, obwohl keine Kante des Runs übernommen wurde.
Ansonsten klappt das aber echt gut!

2022-07-05 08:42 UTC, ElisabethBrandl commented on src/app/services/svg/svg.service.ts
> +                    if (element.label == el.label) {
ja genau ich stelle das gerade nochmal um.

2022-07-18 13:23 UTC, NLueg approved these changes
Funktioniert echt richtig gut! 🚀

2022-07-18 13:27 UTC, NLueg approved these changes

2022-07-18 13:27 UTC, merged