add text shadow
NLueg/FaPra-partielle-sprachen pull request #63
Opened 2022-08-19 06:35 UTC by MarcelSanders

2022-08-19 07:40 UTC, ElisabethBrandl requested changes
Nur als Vorschlag! Kannst ja mal gucken wie du das findest.

2022-08-19 07:40 UTC, ElisabethBrandl commented on src/styles.scss
> +    text-shadow: 1px 1px #ffffff, 2px 2px #ffffff, -1px -1px #ffffff, -2px -2px #ffffff, -3px -3px #ffffff, 3px 3px #ffffff;
Ich hätte das ganze tatsächlich noch minimalistischer gemacht:
text-shadow: 0.5px 0.5px #ffffff, -0.5px 0.5px #ffffff, -0.5px -0.5px #ffffff, 0.5px -0.5px #ffffff;

2022-08-21 17:29 UTC, MarcelSanders commented on src/styles.scss
> +    text-shadow: 1px 1px #ffffff, 2px 2px #ffffff, -1px -1px #ffffff, -2px -2px #ffffff, -3px -3px #ffffff, 3px 3px #ffffff;
Für mich passen beide Varianten. Kann das gerne so übernehmen.

2022-08-22 05:14 UTC, NLueg submitted a review, later dismissed
Finde ich gut!
Ich muss aber sagen, dass ich den stärkeren Text-shadow um einiges besser finde. Mit dem kleineren Shadow ist es trotzdem noch ziemlich schwer den Text zu lesen.
Aber wenn ich da der einzige bin, können wir das natürlich auch wieder zurückändern.

2022-08-23 06:39 UTC, ElisabethBrandl approved these changes

2022-08-23 06:45 UTC, ElisabethBrandl commented
können wir den shadow aber noch symmetrisch machen wie bei mir? gerne größer!

2022-08-23 10:52 UTC, MarcelSanders commented
@NLueg @ElisabethBrandl 
Ich habe dem Shadow jetzt noch einen Blur-Effekt hinzugefügt. Passt es jetzt bei euch so?

2022-08-24 04:35 UTC, NLueg submitted a review, later dismissed
Für mich passt das so! Es muss ja keinen Schönheitswettbewerb gewinnen, sondern sollte nur für eine bessere Lesbarkeit sorgen.
Ich hätte sogar einfach nur `background: white` gesetzt, aber so finde ich es besser, dass man den Pfeil noch im Hintergrund sieht.

2022-08-24 08:36 UTC, ElisabethBrandl approved these changes

2022-08-24 09:59 UTC, NLueg approved these changes

2022-08-24 10:01 UTC, merged